### ISSUE TITLE
Path is Not Accurate (Much like displacement between two points)

### ISSUE THREAD

**Issue by AonCh** [malikdawar/drawroute#12]
Everything is working fine but path is showing like displacement route. It should looks like the path along with roads but is overlapping the roads and showing displacement.

**Comment by malikdawar** [comment]
Tested, it's working fine. I have tested with different scenarios. You were expecting the path through the motorway but unfortunately, Google doesn't provide any clue for the tolls or etc. closing the ticket, please feel free to reach me out through email. thanks!
